### PR TITLE
Competition ui

### PR DESCRIPTION
**Pull request by dcorisis**
created competition UI
added separate html view for each create, edit and delete view
all controllers located in compDisplay.js
added competition service for passing data
STILL TODO:
      determine graph layout
     implement building check boxes

### CODE REVIEW

**Comment by tjdfalcon** [comment]
http://momentjs.com/  You could try using this to display dates. (bower install)

**Comment by tjdfalcon** [comment]
The CreateCompDisplay and EditCompDisplay html look very similar.  It may be possible to use one html file for both views.

**Comment by dcorisis** [comment]
?yea i think we could merge them



DJ Corisis
________________________________

**Comment by mbeck5** [comment]
?DJ, were you working on this at 2 am?

________________________________

**Comment by dcorisis** [comment]
?haha i checked my email at 2 am if thats what you mean


DJ Corisis
________________________________

**Comment by tjdfalcon** [comment]
:100:

**Pull request merged**
